# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-11 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Position', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('MachineID', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=40)),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=40)),
                ('Price', models.IntegerField()),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=40)),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('SaleID', models.AutoField(primary_key=True, serialize=False)),
                ('DateSale', models.DateField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Points', models.IntegerField()),
                ('SMS', models.CharField(max_length=40)),
                ('Active', models.BooleanField()),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Role')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='MachineID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Machine'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
    ]
